# Generated by Django 2.1.3 on 2019-04-28 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=500)),
                ('isbn', models.TextField(max_length=500)),
                ('publisher', models.TextField(max_length=500)),
                ('categories', models.TextField(max_length=500)),
                ('author', models.TextField(max_length=200)),
                ('language', models.TextField(max_length=30)),
                ('genre', models.TextField(max_length=200)),
                ('year', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_languages', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='languages',
        ),
        migrations.AlterField(
            model_name='library',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
